# Configuration Makefile fragment

# Build the libxml2 binding?
# yes | no
WITH_LIBXML_BINDING := yes

# Build the hubbub binding?
# yes | no
WITH_HUBBUB_BINDING := yes

-include Makefile.config.override

