# Sources
DIR_SOURCES := attr.c cdatasection.c characterdata.c comment.c \
	document.c document_type.c doc_fragment.c \
	element.c entity_ref.c implementation.c impllist.c \
	namednodemap.c node.c nodelist.c \
	pi.c string.c text.c

include build/makefiles/Makefile.subdir
